services:
  - type: web
    name: music-moments-final
    runtime: node
    region: oregon
    plan: free
    rootDir: src
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000