services:
  - type: web
    name: songgram
    runtime: node
    rootDir: ./
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production